[package]
name = "gas"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.3.4"
job_scheduler = "*"
tui = "0.16"
termion = "1.5"